In [35]:
import torch
import torch.nn as nn

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 52,  62, -83,  54,  -7, -14])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [12]:
linspace = torch.linspace(3,10, steps = 5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [14]:
logspace = torch.logspace(start= -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
a = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
probabilities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([0, 1, 1, 1, 0, 1, 1, 1, 1, 1])


In [18]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [20]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [22]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [24]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [25]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [27]:
input = torch.zeros(2,3,4) #dimesions
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [28]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias = False)
print(linear(sample))

tensor([4.7872, 3.4334, 0.9934], grad_fn=<SqueezeBackward4>)


In [32]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [36]:


# Specify the size of the vocabulary (number of unique words)
vocab_size = 1000  # Example value, replace with your actual vocabulary size

# Specify the dimension of each embedding vector
embedding_dim = 50  # Example value, adjust as needed

# Create the embedding layer
embedding = nn.Embedding(vocab_size, embedding_dim)

input_indices = torch.LongTensor([[10, 20, 5], [30, 15, 8]])
output_embeddings = embedding(input_indices)
padding_idx = 0
with torch.no_grad():
    embedding.weight[padding_idx] = torch.ones(embedding_dim)  # Set to a custom value



In [37]:
print(embedding)

Embedding(1000, 50)


In [40]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b) #dot matrix
print(torch.matmul(a,b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [43]:
int_64 = torch.randint(1, (3,2)).float()
float_32 = torch.rand(2,3)

result = torch.matmul(int_64, float_32)
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [46]:
a = torch.rand(2,3,5)
x, y, z = a.shape

a = a.view(x,y,z)
b = a.view(x*y,z)
print(a.shape)
print(b.shape)

torch.Size([2, 3, 5])
torch.Size([6, 5])


In [47]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [48]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394
